import os
import folder_paths

from .node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_0, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_0


NODE_CLASS_MAPPINGS = { 
    **NODE_CLASS_MAPPINGS_0, 

    }
NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_0,

    }
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']